// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.fuchsia:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.iOS:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.macOS:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.windows:
        // TODO: Handle this case.
        throw UnimplementedError();
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBnTJlYLJN2lKmKdfgKBYJH1whYMCsF2M',
    appId: '1:516982999814:android:dcc57e25dcaf620ddcec87',
    messagingSenderId: '516982999814',
    projectId: 'weatherappauth-9b2f9',
    storageBucket: 'weatherappauth-9b2f9.appspot.com',
  );
}
